@startuml

package projet.business #GreenYellow/LightGoldenRodYellow {
package projet.business.adapter.out
package projet.business.models
}
package projet.application #2C6E2E {

}
package projet.infrastructure #4C799C {

}
projet.infrastructure -[#red]-> projet.business.adapter.out
projet.infrastructure -[#red]-> projet.business.models
projet.infrastructure -[#red]-+ projet.application
note top of projet.application
Utilisation non autorisée
end note
@enduml
