@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center

box "Business" #GreenYellow/LightGoldenRodYellow
participant PersonneUseCase [
    =PersonneUseCase
    ----
    ""Personne findById(id String)""
]
participant RestPersonneOut [
    =RestPersonneOut
    ----
    ""Personne findById(id String)""
]
participant CalculNbJoursDNaissRule [
    =CalculNbJoursDNaissRule
    ----
    ""int get(LocalDate dNaiss)""
]
participant CiviliteRule [
    =CiviliteRule
    ----
    ""String get(String nss)""
]
end box

[-> PersonneUseCase ++ : Cas usage
PersonneUseCase -> RestPersonneOut --++: Appel du service rest dans le réseau
RestPersonneOut -> PersonneUseCase --++:
PersonneUseCase -> CalculNbJoursDNaissRule --++: Calcul le nombre de jours depuis la date de naissance
CalculNbJoursDNaissRule -> PersonneUseCase --++
PersonneUseCase -> CiviliteRule --++: Retourne la civilité en fonction du premier chiffre nss
CiviliteRule -> PersonneUseCase --++
[<- PersonneUseCase -- : retourne une personne
@enduml
