@startuml
title: Diagramme des éléments
package projet.business #GreenYellow/LightGoldenRodYellow {
  package projet.business.adapter.out {
  interface RestPersonneOut {
    Personne findById(id String)
  }
  }
  package projet.business.adapter.in {
    interface PersonneIn {
      Personne findById(id String)
    }
    }
  package projet.business.models {
    class Personne{
    }
  }
    package projet.business.rules {
        class CiviliteRule{
            +String get(String nss)
        }
        class CalculNbJoursDNaissRule{
            +int get(LocalDate dNaiss)
        }
      }
      package projet.business.service {
          class PersonneServiceDefault implements projet.business.adapter.in.PersonneIn {
          .. Référence au service infrastructure ..
          - <<final>> RestPersonneOut restPersonneOut
          .. constructor ..
          PersonneServiceDefault(RestPersonneOut restPersonneOut)
          .. Override ..
          +Personne findById(id String)
          }
        }
}

}
@enduml
