@startuml
title diagramme des dépendences du module `infrastructure`
package projet{
package business #GreenYellow/LightGoldenRodYellow {
package business.adapter.out{
}
package business.models
}
package application #2C6E2E {

}
package infrastructure #4C799C {

}
}
note left of infrastructure
<:26d4:> "<b>infrastructure</b> ne peut pas utiliser un objet d'<b>application</b>"
end note
infrastructure --[#red]--> business.adapter.out
infrastructure --[#red]--> business.models
infrastructure --[#red]--> application :  <:26d4:>

@enduml
