@startuml
title diagramme des dépendences du module `infrastructure`
package projet{
package infrastructure #4C799C {

}
package application #2C6E2E {

}
package business #GreenYellow/LightGoldenRodYellow {
package business.adapter.out{
}
package business.models
}
}

infrastructure --[#red]--> business.adapter.out
infrastructure --[#red]--> business.models

application <=[#red]= infrastructure : \t<:26d4:> Les objets du module <b>infrastructure</b>  \nne peuvent pas utiliser \ndes objets du module d'<b>application</b>

@enduml
